[package]
name = "home_speak"
version = "0.1.0"
authors = ["David Michael Weis <dweis7@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
google_tts = { git = "https://github.com/dmweis/google_tts", branch = "async" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
simplelog = "0.11"
log = "0.4"
rodio = "0.14"
clap = "3.0.0-beta.1"
sha2 = "0.9"
warp = "0.2"
crossbeam-channel = "0.4"
tokio = { version = "0.2", features = ["macros", "rt-core"] }
bytes = "0.5"
