[package]
name = "home_speak"
version = "0.1.0"
authors = ["David Michael Weis <dweis7@gmail.com>"]
edition = "2021"
publish = false
default-run = "home_speak_server"


[dependencies]
google_tts = { git = "https://github.com/dmweis/google_tts", branch = "main" }
azure_tts = { git = "https://github.com/dmweis/azure_tts", branch = "main" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = "0.11"
log = "0.4"
rodio = "0.14"
structopt = "0.3"
sha2 = "0.10"
crossbeam-channel = "0.5"
bytes = "1.1"
config = "0.11"
thiserror = "1.0"
local-ip-address = "0.4.4"
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
