[package]
name = "home_speak"
version = "0.1.0"
authors = ["David Michael Weis <dweis7@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
google_tts = { git = "https://github.com/dmweis/google_tts", branch = "main" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = "0.11"
log = "0.4"
rodio = "0.14"
structopt = "0.3"
sha2 = "0.10"
warp = "0.3"
crossbeam-channel = "0.5"
tokio = { version = "1.15", features = ["full"] }
bytes = "1.1"
config = "0.11"
