#!/usr/bin/env bash

set -eo pipefail

if (( "$EUID" == 0 )); then
  echo "Please do not run as root"
  exit
fi


cargo install --path . --bin home_speak_server

# This script is all kinds of yikes
# Replace this default settings with something sensible

mkdir -p /home/$(whoami)/.config/home_speak
touch /home/$(whoami)/.config/home_speak/settings.yaml


cat <<EOT | sudo tee /etc/systemd/system/home_speak.service > /dev/null
[Unit]
Description=Home Speak
After=network-online.target nss-lookup.target
Wants=network-online.target

[Service]
User=$(whoami)
Type=simple
Restart=on-failure
RestartSec=5s
ExecStart=/home/$(whoami)/.cargo/bin/home_speak_server --config /home/$(whoami)/.config/home_speak/settings

[Install]
WantedBy=default.target
EOT

sudo systemctl daemon-reload
sudo systemctl enable home_speak
sudo systemctl restart home_speak
