tts_service_config:
  cache_dir_path: "audio_cache"
  tts_service: "Azure"
server_config:
  host: "0.0.0.0"
  port: 3000
assistant_config:
  name: "Joy"
  primary_user_name: "User"
blinds:
  url: "http://blindspi.local:8080"
