tts_service_config:
  google_api_key: ""
  azure_api_key: ""
  eleven_labs_api_key: ""
  cache_dir_path: "/var/cache/home_speak/audio_cache"
  tts_service: "Azure"
assistant_config:
  name: "Joy"
  primary_user_name: "David"
mqtt:
  base_route: "test_speech"
  broker_host: "homepi.local"
  client_id: "home_speak_test_instance"
audio_repository_path: "/etc/home_speak/audio/"
